version: "3.8"
services:
  release-image:
    image: registry.gitlab.com/librefoodpantry/spikeathons/lfp-spikeathon-summer-2020/release-image:2
    environment:
      # Space delimited list of tags that reference images in your
      # local Docker environment to be released. These tags must encode
      # the repository where the referenced image will ultimately be
      # published.
      # e.g., registry/user/image:build registry/user/image2:build .
      - IMAGES_TO_RELEASE=

      # Leave these blank; they are set in .env; we just need to pass them through
      - GIT_AUTHOR_NAME
      - EMAIL
    volumes:
      - "${DOCKER_SOCK}:/var/run/docker.sock:ro"
      - "${DOCKER_EXE}:/usr/local/bin/docker:ro"
      - "${PWD}:/app"

